version: "3.1"

services:

  server:
    build: ./server
    restart: always
    ports:
      - 3000:3000
  
  display:
    build: ./display
    restart: always
    ports:
      - 5678:80
  
  controller:
    build: ./controller
    restart: always
    ports:
      - 1234:80
